parser:
  emojis:
    named:
      smile: ðŸ˜„
      smiley: ðŸ˜ƒ
      grinning: ðŸ˜€
      blush: ðŸ˜Š
      wink: ðŸ˜‰
      heart_eyes: ðŸ˜
      kissing_heart: ðŸ˜˜
      kissing_closed_eyes: ðŸ˜š
      kissing: ðŸ˜—
      kissing_smiling_eyes: ðŸ˜™
      stuck_out_tongue_winking_eye: ðŸ˜œ
      stuck_out_tongue_closed_eyes: ðŸ˜
      stuck_out_tongue: ðŸ˜›
      flushed: ðŸ˜³
      grin: ðŸ˜
      pensive: ðŸ˜”
      relieved: ðŸ˜Œ
      unamused: ðŸ˜’
      disappointed: ðŸ˜ž
      persevere: ðŸ˜£
      cry: ðŸ˜¢
      joy: ðŸ˜‚
      sob: ðŸ˜­
      sleepy: ðŸ˜ª
      disappointed_relieved: ðŸ˜¥
      cold_sweat: ðŸ˜°
      sweat_smile: ðŸ˜…
      sweat: ðŸ˜“
      weary: ðŸ˜©
      tired_face: ðŸ˜«
      fearful: ðŸ˜¨
      scream: ðŸ˜±
      angry: ðŸ˜ 
      rage: ðŸ˜¡
      confounded: ðŸ˜–
      laughing: ðŸ˜†
      satisfied: ðŸ˜†
      yum: ðŸ˜‹
      mask: ðŸ˜·
      sunglasses: ðŸ˜Ž
      sleeping: ðŸ˜´
      dizzy_face: ðŸ˜µ
      astonished: ðŸ˜²
      worried: ðŸ˜Ÿ
      frowning: ðŸ˜¦
      anguished: ðŸ˜§
      smiling_imp: ðŸ˜ˆ
      open_mouth: ðŸ˜®
      neutral_face: ðŸ˜
      confused: ðŸ˜•
      hushed: ðŸ˜¯
      no_mouth: ðŸ˜¶
      innocent: ðŸ˜‡
      smirk: ðŸ˜
      expressionless: ðŸ˜‘
      smiley_cat: ðŸ˜º
      smile_cat: ðŸ˜¸
      heart_eyes_cat: ðŸ˜»
      kissing_cat: ðŸ˜½
      smirk_cat: ðŸ˜¼
      scream_cat: ðŸ™€
      crying_cat_face: ðŸ˜¿
      joy_cat: ðŸ˜¹
      pouting_cat: ðŸ˜¾
      cat: ðŸ±
      mouse: ðŸ­
      cow: ðŸ®
      monkey_face: ðŸµ
      hourglass: âŒ›
      watch: âŒš
      coffee: â˜•
      exclamation: â—
      question: â“

    aliases:
      # Emoticons -> Emoji mapping.
      mad:
        - '>:('
        - '>:-('
      blush:
        - :")
        - :-")
      broken_heart:
        - </3
        - <\3
      confused:
        # disabled because of conflicts with links
        # - :\
        # - :/
        - :-\
        - :-/
      cry:
        - :'(
        - :'-(
        - :,(
        - :,-(
      frowning:
        - :(
        - :-(
      heart:
        - <3
      imp:
        - ']:('
        - ']:-('
      innocent:
        - o:)
        - O:)
        - o:-)
        - O:-)
        - 0:)
        - 0:-)
      joy:
        - :')
        - :'-)
        - :,)
        - :,-)
        - :'D
        - :'-D
        - :,D
        - :,-D
      kissing:
        - :*
        - :-*
      laughing:
        - x-)
        - X-)
      neutral_face:
        - :|
        - :-|
      open_mouth:
        - :o
        - :-o
        - :O
        - :-O
      rage:
        - :@
        - :-@
      smile:
        - :D
        - :-D
      smiley:
        - :)
        - :-)
      smiling_imp:
        - ']:)'
        - ']:-)'
      sob:
        - :,'(
        - :,'-(
        - ;(
        - ;-(
      stuck_out_tongue:
        - :P
        - :-P
      sunglasses:
        - 8-)
        - B-)
      sweat:
        - ',:('
        - ',:-('
      sweat_smile:
        - ',:)'
        - ',:-)'
      unamused:
        - :s
        - :-S
        - :z
        - :-Z
        - :$
        - :-$
      wink:
        - ;)
        - ;-)
