parser:
  emojis:
    named:
      smile: ðŸ˜„
      smiley: ðŸ˜ƒ
      grinning: ðŸ˜€
      blush: ðŸ˜Š
      wink: ðŸ˜‰
      heart_eyes: ðŸ˜
      kissing_heart: ðŸ˜˜
      kissing_closed_eyes: ðŸ˜š
      kissing: ðŸ˜—
      kissing_smiling_eyes: ðŸ˜™
      stuck_out_tongue_winking_eye: ðŸ˜œ
      stuck_out_tongue_closed_eyes: ðŸ˜
      stuck_out_tongue: ðŸ˜›
      flushed: ðŸ˜³
      grin: ðŸ˜
      pensive: ðŸ˜”
      relieved: ðŸ˜Œ
      unamused: ðŸ˜’
      disappointed: ðŸ˜ž
      persevere: ðŸ˜£
      cry: ðŸ˜¢
      joy: ðŸ˜‚
      sob: ðŸ˜­
      sleepy: ðŸ˜ª
      disappointed_relieved: ðŸ˜¥
      cold_sweat: ðŸ˜°
      sweat_smile: ðŸ˜…
      sweat: ðŸ˜“
      weary: ðŸ˜©
      tired_face: ðŸ˜«
      fearful: ðŸ˜¨
      scream: ðŸ˜±
      angry: ðŸ˜ 
      rage: ðŸ˜¡
      confounded: ðŸ˜–
      laughing: ðŸ˜†
      satisfied: ðŸ˜†
      yum: ðŸ˜‹
      mask: ðŸ˜·
      sunglasses: ðŸ˜Ž
      sleeping: ðŸ˜´
      dizzy_face: ðŸ˜µ
      astonished: ðŸ˜²
      worried: ðŸ˜Ÿ
      frowning: ðŸ˜¦
      anguished: ðŸ˜§
      smiling_imp: ðŸ˜ˆ
      open_mouth: ðŸ˜®
      neutral_face: ðŸ˜
      confused: ðŸ˜•
      hushed: ðŸ˜¯
      no_mouth: ðŸ˜¶
      innocent: ðŸ˜‡
      smirk: ðŸ˜
      expressionless: ðŸ˜‘
      smiley_cat: ðŸ˜º
      smile_cat: ðŸ˜¸
      heart_eyes_cat: ðŸ˜»
      kissing_cat: ðŸ˜½
      smirk_cat: ðŸ˜¼
      scream_cat: ðŸ™€
      crying_cat_face: ðŸ˜¿
      joy_cat: ðŸ˜¹
      pouting_cat: ðŸ˜¾
      sparkles: âœ¨
      fist: âœŠ
      hand: âœ‹
      raised_hand: âœ‹
      cat: ðŸ±
      mouse: ðŸ­
      cow: ðŸ®
      monkey_face: ðŸµ
      star: â­
      zap: âš¡
      umbrella: â˜”
      hourglass: âŒ›
      watch: âŒš
      black_joker: ðŸƒ
      mahjong: ðŸ€„
      coffee: â˜•
      anchor: âš“
      wheelchair: â™¿
      negative_squared_cross_mark: âŽ
      white_check_mark: âœ…
      loop: âž¿
      aries: â™ˆ
      taurus: â™‰
      gemini: â™Š
      cancer: â™‹
      leo: â™Œ
      virgo: â™
      libra: â™Ž
      scorpius: â™
      sagittarius: â™
      capricorn: â™‘
      aquarius: â™’
      pisces: â™“
      x: âŒ
      exclamation: â—
      heavy_exclamation_mark: â—
      question: â“
      grey_exclamation: â•
      grey_question: â”
      heavy_plus_sign: âž•
      heavy_minus_sign: âž–
      heavy_division_sign: âž—
      curly_loop: âž°
      black_medium_small_square: â—¾
      white_medium_small_square: â—½
      black_circle: âš«
      white_circle: âšª
      white_large_square: â¬œ
      black_large_square: â¬›

    aliases:
      # Emoticons -> Emoji mapping.
      mad:
        - '>:('
        - '>:-('
      blush:
        - :")
        - :-")
      broken_heart:
        - </3
        - <\3
      confused:
        # disabled because of conflicts with links
        # - :\
        # - :/
        - :-\
        - :-/
      cry:
        - :'(
        - :'-(
        - :,(
        - :,-(
      frowning:
        - :(
        - :-(
      heart:
        - <3
      imp:
        - ']:('
        - ']:-('
      innocent:
        - o:)
        - O:)
        - o:-)
        - O:-)
        - 0:)
        - 0:-)
      joy:
        - :')
        - :'-)
        - :,)
        - :,-)
        - :'D
        - :'-D
        - :,D
        - :,-D
      kissing:
        - :*
        - :-*
      laughing:
        - x-)
        - X-)
      neutral_face:
        - :|
        - :-|
      open_mouth:
        - :o
        - :-o
        - :O
        - :-O
      rage:
        - :@
        - :-@
      smile:
        - :D
        - :-D
      smiley:
        - :)
        - :-)
      smiling_imp:
        - ']:)'
        - ']:-)'
      sob:
        - :,'(
        - :,'-(
        - ;(
        - ;-(
      stuck_out_tongue:
        - :P
        - :-P
      sunglasses:
        - 8-)
        - B-)
      sweat:
        - ',:('
        - ',:-('
      sweat_smile:
        - ',:)'
        - ',:-)'
      unamused:
        - :s
        - :-S
        - :z
        - :-Z
        - :$
        - :-$
      wink:
        - ;)
        - ;-)
