# This settings are not used directly. Those are taken by apps to generate local sets.

setting_schemas:
  markup:

    markup_cut:
      priority: 10
      type: boolean
      as: cut # rename setting key after fetch
      default: false

    markup_emphasis:
      priority: 10
      type: boolean
      as: emphasis
      default: true

    markup_footnote:
      priority: 10
      type: boolean
      as: footnote
      default: true

    markup_heading:
      priority: 10
      type: boolean
      as: heading
      default: true

    markup_image:
      priority: 10
      type: boolean
      as: image
      default: true

    markup_attachment:
      priority: 10
      type: boolean
      as: attachment
      default: true

    markup_link:
      priority: 10
      type: boolean
      as: link
      default: true

    markup_list:
      priority: 10
      type: boolean
      as: list
      default: true

    markup_hr:
      priority: 10
      type: boolean
      as: hr
      default: true

    markup_code:
      priority: 10
      type: boolean
      as: code
      default: true

    markup_quote:
      priority: 10
      type: boolean
      as: quote
      default: true

    markup_emoji:
      priority: 10
      type: boolean
      as: emoji
      default: true

    markup_spoiler:
      priority: 10
      type: boolean
      as: spoiler
      default: true

    markup_link_to_title:
      priority: 10
      type: boolean
      as: link_to_title
      default: true

    markup_link_to_snippet:
      priority: 10
      type: boolean
      as: link_to_snippet
      default: true

    markup_sub:
      priority: 10
      type: boolean
      as: sub
      default: true

    markup_sup:
      priority: 10
      type: boolean
      as: sup
      default: true

    markup_table:
      priority: 10
      type: boolean
      as: table
      default: true
